# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foundation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Foundation

  target 'FoundationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Foundation-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Foundation-tvOS

  target 'Foundation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
